### ISSUE TITLE
cleanup: return null if the deduce function is not implemented for a builtin

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/cairo-zig#106]
### Description
For example, the range check builtin does not have the `deduce` function, as we can see in the [python](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/lang/builtins/bitwise/bitwise_builtin_runner.py) implementation, returns `None` in the [Rust](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/vm/runners/builtin_runner/range_check.rs#L107) implementation. But the builtin runner iterates over each builtin and [calls](https://github.com/keep-starknet-strange/cairo-zig/blob/b119ba4a2056441f76ed72bb2b6e3547cdc9b0e1/src/vm/core.zig#L437) the `deduce` function. Implement a function that returns `null` or treat the unimplemented path correctly. Make sure the runner iterates correctly over the builtins.

**Comment by Deecellar** [comment]
I personally prefer errors for this since unimplemented paths are "errors" of sort, that are recoverable

instead of using catch, one would use 

`if(possible_error) |success_path_value| {} else |err| {}`

**Comment by tcoratger** [comment]
@Deecellar @lana-shanghai I just linked a PR to this issue you can look. I have decided to return a `null` for all implementations not yet done. 

I know that in the Zig ideal, errors represent a type in their own right that is often relevant to use. However in this case, a built in that does not have a `deduceMemoryCell` function should rather return a `null` than an error because it is not really an error but rather something that does not exist. 

Moreover, in the implementation of `deduceMemoryCell` for example for the built in keccak, there is the possibility under certain conditions that the function returns a `null` and for me it is quite similar in the approach. 

Afterwards this is only my opinion and in the `deduceMemoryCell` switch of the `BuiltinRunner` structure we can also return a non implemented error for the built in range check for example.

**Comment by Deecellar** [comment]
Something that doesn't exist when it should for me is kind of an error, but I get the logic behind it, There are zig API that uses this approach, Specially if it's the only error that it can have.
