### ISSUE TITLE
feat: implement range check builtin

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/cairo-zig#5]
Copying a value to a range-checked cell allows to see if is inside a range `[0; 2**128)`.

See the [Go](https://github.com/NethermindEth/cairo-vm-go/blob/main/pkg/vm/builtins/range_check.go) and [Rust](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/vm/runners/builtin_runner/range_check.rs) implementations.

**Comment by oxlime** [comment]
can i take this one

**Comment by abdelhamidbakhta** [comment]
> can i take this one

Sure thing, assigned to you

**Comment by tcoratger** [comment]
@oxlime For your information, with the recent work that have been done, this implementation can be done directly into this file: https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/builtins/builtin_runner/range_check.zig

**Comment by oxlime** [comment]
@tcoratger 
Any reason to not use the zig std.math library for shl?
https://github.com/ziglang/zig/blob/91e117697ad90430d9266203415712b6cc59f669/lib/std/math.zig#L470

**Comment by tcoratger** [comment]
> @tcoratger Any reason to not use the zig std.math library for shl? https://github.com/ziglang/zig/blob/91e117697ad90430d9266203415712b6cc59f669/lib/std/math.zig#L470

@oxlime Yes, it's true that it's tempting because Zig has the specialty of having natively integrated many utility libraries into `std` and it is therefore often quite useless to develop them from scratch.

I think this is a use we can consider in the future to replace certain operations in a safe way using `std`, but for now the mathematical operations, in my opinion, must satisfy the rules of the base field for the Stark curve (Felt252) to be compatible with all types of the codebase and therefore these operations must be implemented in the following [file](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/math/fields/fields.zig) like the other operations that are already there, what do you think @abdelhamidbakhta?

**Comment by oxlime** [comment]
@tcoratger i see, ty
